apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: sixfeb-dev
data:
  spring.datasource.username: "cm9vdA=="
  spring.datasource.password: "cGFzc3dvcmQ="
  spring.datasource.url: "amRiYzpteXNxbDovL2hvc3QubWluaWt1YmUuaW50ZXJuYWw6MzMwNy9lbXBsb3llZXM="
