spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3307/employees
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /api/v2/
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.transaction.support: TRACE
    com.zaxxer.hikari.HikariConfig: TRACE
    com.zaxxer.hikari: TRACE
    th.co.prior.training.spring: ERROR

app:
  kafka:
    server: localhost:29092
server:
  servlet:
    context-path: /app
  port: 8080
